service: aws-node-rest-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
