# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Node.js environment
      uses: actions/setup-node@v1

    - name: Install Serverless Framework
      run: npm i -g serverless

  #  - name: Configure AWS credentials from Test account
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-1
