# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  build:


    runs-on: ubuntu-latest
    env: 
      region1 : ap-southeast-2
      prefix : awesome
 
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Node.js environment
      uses: actions/setup-node@v1

    - name: Install Serverless Framework
      run: npm i -g serverless

    - run: npm install

    # - name: serverless deploy
    #   uses: serverless/github-action@master

    - name: create ENV file
      run: |
        cat > .env <<EOF
        prefix= ${{ env.prefix }}        
        ${{ secrets.ENV }}
        cat .env
        EOF

      

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Deploy
      run: sls deploy -s dev
